if GetLocale() ~= "deDE" then return end

local o = mOnWardrobe
local c = {}
o.categorization = c
o.EXPS = {'Vanilla', 'Burning Crusade', 'WotLK', 'Cataclysm', 'Mists of Pandaria', 'Draenor', 'Legion'}
o.PARTY = {'Dungeon', 'Raid'}

c["Ahn'kahet: Das Alte Königreich"] = {3, 1}
c["Angriff auf die Violette Festung"] = {7, 1}
c["Auchenaikrypta"] = {2, 1}
c["Auchindoun"] = {6, 1}
c["Azjol-Nerub"] = {3, 1}
c["Baradinfestung"] = {4, 2}
c["Die Rabenwehr"] = {7, 1}
c["Der Schwarze Tempel "] = {2, 2}
c["Tiefschwarze Grotte"] = {1, 1}
c["Schwarzfelshöhlen"] = {4, 1}
c["Schwarzfelstiefen"] = {1, 1}
c["Schwarzfelsgießerei"] = {6, 2}
c["Pechschwingenabstieg"] = {4, 2}
c["Pechschwingenhort"] = {1, 2}
c["Blutschlägermine"] = {6, 1}
c["Verheerten Inseln"] = {7, 2}
c["Der Hof der Sterne"] = {7, 1}
c["Das Finsterherzdickicht"] = {7, 1}
c["Die Todesminen"] = {1, 1}
c["Düsterbruch"] = {1, 1}
c["Draenor"] = {6, 2}
c["Drachenseele"] = {4, 2}
c["Feste Drak'Tharon"] = {3, 1}
c["Die Endzeit"] = {4, 1}
c["Das Auge Azsharas"] = {7, 1}
c["Feuerlande"] = {4, 2}
c["Das Tor der Untergehenden Sonne"] = {5, 1}
c["Gnomeregan"] = {1, 1}
c["Grim Batol"] = {4, 1}
c["Grimmgleisdepot"] = {6, 1}
c["Gruuls Unterschlupf"] = {2, 2}
c["Gundrak"] = {3, 1}
c["Hallen der Blitze"] = {3, 1}
c["Hallen des Ursprungs"] = {4, 1}
c["Hallen der Reflexion"] = {3, 1}
c["Hallen des Steins"] = {3, 1}
c["Die Hallen der Tapferkeit"] = {7, 1}
c["Das Herz der Angst"] = {5, 2}
c["Höllenfeuerzitadelle"] = {6, 2}
c["Höllenfeuerbollwerk"] = {2, 1}
c["Hochfels"] = {6, 2}
c["Stunde des Zwielichts"] = {4, 1}
c["Die Eiskronenzitadelle"] = {3, 2}
c["Eisendocks"] = {6, 1}
c["Karazhan"] = {2, 2}
c["Die Verlorene Stadt der Tol'vir"] = {4, 1}
c["Untere Schwarzfelsspitze"] = {1, 1}
c["Terrasse der Magister"] = {2, 1}
c["Magtheridons Kammer"] = {2, 2}
c["Managruft"] = {2, 1}
c["Maraudon"] = {1, 1}
c["Schlund der Seelen"] = {7, 1}
c["Mogu'shanpalast"] = {5, 1}
c["Mogu'shangewölbe"] = {5, 2}
c["Geschmolzener Kern"] = {1, 2}
c["Naxxramas"] = {3, 2}
c["Neltharions Hort"] = {7, 1}
c["Vorgebirge des Alten Hügellands"] = {2, 1}
c["Onyxias Hort"] = {3, 2}
c["Pandaria"] = {5, 2}
c["Grube von Saron"] = {3, 1}
c["Der Flammenschlund"] = {1, 1}
c["Hügel der Klingenhauer"] = {1, 1}
c["Kral der Klingenhauer"] = {1, 1}
c["Ruinen von Ahn'Qiraj"] = {1, 2}
c["Scharlachrote Hallen"] = {1, 1}
c["Das Scharlachrote Kloster"] = {1, 1}
c["Scholomance"] = {1, 1}
c["Höhle des Schlangenschreins"] = {2, 2}
c["Sethekkhallen"] = {2, 1}
c["Shado-Pan-Kloster"] = {5, 1}
c["Schattenlabyrinth"] = {2, 1}
c["Burg Schattenfang"] = {1, 1}
c["Schattenmondgrabstätte"] = {6, 1}
c["Die Belagerung des Niuzaotempels"] = {5, 1}
c["Schlacht um Orgrimmar"] = {5, 2}
c["Himmelsnadel"] = {6, 1}
c["Brauerei Sturmbräu"] = {5, 1}
c["Stratholme"] = {1, 1}
c["Sonnenbrunnenplateau"] = {2, 2}
c["Ahn'Qiraj"] = {1, 2}
c["Tempel der Jadeschlange"] = {5, 1}
c["Terrasse des Endlosen Frühlings"] = {5, 2}
c["Die Arkatraz"] = {2, 1}
c["Der Arkus"] = {7, 1}
c["Die Bastion des Zwielichts"] = {4, 2}
c["Die Schlacht um den Hyjal"] = {2, 2}
c["Der Schwarze Morast"] = {2, 1}
c["Der Blutkessel"] = {2, 1}
c["Die Botanika"] = {2, 1}
c["Das Ausmerzen von Stratholme"] = {3, 1}
c["Der Smaragdgrüne Alptraum"] = {7, 2}
c["Der Immergrüne Flor"] = {6, 1}
c["Festung der Stürme"] = {2, 2}
c["Das Auge der Ewigkeit"] = {3, 2}
c["Die Seelenschmiede"] = {3, 1}
c["Die Mechanar"] = {2, 1}
c["Der Nexus"] = {3, 1}
c["Die Nachtfestung"] = {7, 2}
c["Das Obsidiansanktum"] = {3, 2}
c["Das Oculus"] = {3, 1}
c["Das Rubinsanktum"] = {3, 2}
c["Die Zerschmetterten Hallen"] = {2, 1}
c["Die Sklavenunterkünfte"] = {2, 1}
c["Die Dampfkammer"] = {2, 1}
c["Das Verlies"] = {1, 1}
c["Der Steinerne Kern"] = {4, 1}
c["Tempel von Atal'Hakkar"] = {1, 1}
c["Der Tiefensumpf"] = {2, 1}
c["Die Violette Festung"] = {3, 1}
c["Der Vortexgipfel"] = {4, 1}
c["Der Thron des Donners"] = {5, 2}
c["Thron der Vier Winde"] = {4, 2}
c["Thron der Gezeiten"] = {4, 1}
c["Prüfung des Champions"] = {3, 1}
c["Prüfung des Kreuzfahrers"] = {3, 2}
c["Uldaman"] = {1, 1}
c["Ulduar"] = {3, 2}
c["Obere Schwarzfelsspitze"] = {6, 1}
c["Burg Utgarde"] = {3, 1}
c["Turm Utgarde"] = {3, 1}
c["Archavons Kammer"] = {3, 2}
c["Das Verlies der Wächterinnen"] = {7, 1}
c["Die Höhlen des Wehklagens"] = {1, 1}
c["Brunnen der Ewigkeit"] = {4, 1}
c["Zul'Aman"] = {4, 1}
c["Zul'Farrak"] = {1, 1}
c["Zul'Gurub"] = {4, 1}