local o = mOnWardrobe
local c = {}
o.categorization = c
o.EXPS = {'Vanilla', 'Burning Crusade', 'WotLK', 'Cataclysm', 'Mists of Pandaria', 'Draenor', 'Legion'}
o.PARTY = {'Dungeon', 'Raid'}

c["Ahn'kahet: The Old Kingdom"] = {3, 1}
c["Assault on Violet Hold"] = {7, 1}
c["Auchenai Crypts"] = {2, 1}
c["Auchindoun"] = {6, 1}
c["Azjol-Nerub"] = {3, 1}
c["Baradin Hold"] = {4, 2}
c["Black Rook Hold"] = {7, 1}
c["Black Temple"] = {2, 2}
c["Blackfathom Deeps"] = {1, 1}
c["Blackrock Caverns"] = {4, 1}
c["Blackrock Depths"] = {1, 1}
c["Blackrock Foundry"] = {6, 2}
c["Blackwing Descent"] = {4, 2}
c["Blackwing Lair"] = {1, 2}
c["Bloodmaul Slag Mines"] = {6, 1}
c["Broken Isles"] = {7, 2}
c["Court of Stars"] = {7, 1}
c["Darkheart Thicket"] = {7, 1}
c["Deadmines"] = {1, 1}
c["Dire Maul"] = {1, 1}
c["Draenor"] = {6, 2}
c["Dragon Soul"] = {4, 2}
c["Drak'Tharon Keep"] = {3, 1}
c["End Time"] = {4, 1}
c["Eye of Azshara"] = {7, 1}
c["Firelands"] = {4, 2}
c["Gate of the Setting Sun"] = {5, 1}
c["Gnomeregan"] = {1, 1}
c["Grim Batol"] = {4, 1}
c["Grimrail Depot"] = {6, 1}
c["Gruul's Lair"] = {2, 2}
c["Gundrak"] = {3, 1}
c["Halls of Lightning"] = {3, 1}
c["Halls of Origination"] = {4, 1}
c["Halls of Reflection"] = {3, 1}
c["Halls of Stone"] = {3, 1}
c["Halls of Valor"] = {7, 1}
c["Heart of Fear"] = {5, 2}
c["Hellfire Citadel"] = {6, 2}
c["Hellfire Ramparts"] = {2, 1}
c["Highmaul"] = {6, 2}
c["Hour of Twilight"] = {4, 1}
c["Icecrown Citadel"] = {3, 2}
c["Iron Docks"] = {6, 1}
c["Karazhan"] = {2, 2}
c["Lost City of the Tol'vir"] = {4, 1}
c["Lower Blackrock Spire"] = {1, 1}
c["Magisters' Terrace"] = {2, 1}
c["Magtheridon's Lair"] = {2, 2}
c["Mana-Tombs"] = {2, 1}
c["Maraudon"] = {1, 1}
c["Maw of Souls"] = {7, 1}
c["Mogu'shan Palace"] = {5, 1}
c["Mogu'shan Vaults"] = {5, 2}
c["Molten Core"] = {1, 2}
c["Naxxramas"] = {3, 2}
c["Neltharion's Lair"] = {7, 1}
c["Old Hillsbrad Foothills"] = {2, 1}
c["Onyxia's Lair"] = {3, 2}
c["Pandaria"] = {5, 2}
c["Pit of Saron"] = {3, 1}
c["Ragefire Chasm"] = {1, 1}
c["Razorfen Downs"] = {1, 1}
c["Razorfen Kraul"] = {1, 1}
c["Ruins of Ahn'Qiraj"] = {1, 2}
c["Scarlet Halls"] = {1, 1}
c["Scarlet Monastery"] = {1, 1}
c["Scholomance"] = {1, 1}
c["Serpentshrine Cavern"] = {2, 2}
c["Sethekk Halls"] = {2, 1}
c["Shado-Pan Monastery"] = {5, 1}
c["Shadow Labyrinth"] = {2, 1}
c["Shadowfang Keep"] = {1, 1}
c["Shadowmoon Burial Grounds"] = {6, 1}
c["Siege of Niuzao Temple"] = {5, 1}
c["Siege of Orgrimmar"] = {5, 2}
c["Skyreach"] = {6, 1}
c["Stormstout Brewery"] = {5, 1}
c["Stratholme"] = {1, 1}
c["Sunwell Plateau"] = {2, 2}
c["Temple of Ahn'Qiraj"] = {1, 2}
c["Temple of the Jade Serpent"] = {5, 1}
c["Terrace of Endless Spring"] = {5, 2}
c["The Arcatraz"] = {2, 1}
c["The Arcway"] = {7, 1}
c["The Bastion of Twilight"] = {4, 2}
c["The Battle for Mount Hyjal"] = {2, 2}
c["The Black Morass"] = {2, 1}
c["The Blood Furnace"] = {2, 1}
c["The Botanica"] = {2, 1}
c["The Culling of Stratholme"] = {3, 1}
c["The Emerald Nightmare"] = {7, 2}
c["The Everbloom"] = {6, 1}
c["The Eye"] = {2, 2}
c["The Eye of Eternity"] = {3, 2}
c["The Forge of Souls"] = {3, 1}
c["The Mechanar"] = {2, 1}
c["The Nexus"] = {3, 1}
c["The Nighthold"] = {7, 2}
c["The Obsidian Sanctum"] = {3, 2}
c["The Oculus"] = {3, 1}
c["The Ruby Sanctum"] = {3, 2}
c["The Shattered Halls"] = {2, 1}
c["The Slave Pens"] = {2, 1}
c["The Steamvault"] = {2, 1}
c["The Stockade"] = {1, 1}
c["The Stonecore"] = {4, 1}
c["The Temple of Atal'hakkar"] = {1, 1}
c["The Underbog"] = {2, 1}
c["The Violet Hold"] = {3, 1}
c["The Vortex Pinnacle"] = {4, 1}
c["Throne of Thunder"] = {5, 2}
c["Throne of the Four Winds"] = {4, 2}
c["Throne of the Tides"] = {4, 1}
c["Trial of the Champion"] = {3, 1}
c["Trial of the Crusader"] = {3, 2}
c["Uldaman"] = {1, 1}
c["Ulduar"] = {3, 2}
c["Upper Blackrock Spire"] = {6, 1}
c["Utgarde Keep"] = {3, 1}
c["Utgarde Pinnacle"] = {3, 1}
c["Vault of Archavon"] = {3, 2}
c["Vault of the Wardens"] = {7, 1}
c["Wailing Caverns"] = {1, 1}
c["Well of Eternity"] = {4, 1}
c["Zul'Aman"] = {4, 1}
c["Zul'Farrak"] = {1, 1}
c["Zul'Gurub"] = {4, 1}
