if GetLocale() ~= "frFR" then return end

local o = mOnWardrobe
local c = {}
o.categorization = c
o.EXPS = {'Vanilla', 'Burning Crusade', 'WotLK', 'Cataclysm', 'Mists of Pandaria', 'Draenor', 'Legion'}
o.PARTY = {'Dungeon', 'Raid'}

c["Ahn’kahet : l’Ancien royaume"] = {3, 1}
c["Assaut sur le fort Pourpre"] = {7, 1}
c["Cryptes Auchenaï"] = {2, 1}
c["Auchindoun"] = {6, 1}
c["Azjol-Nérub"] = {3, 1}
c["Bastion de Baradin"] = {4, 2}
c["Bastion du Freux"] = {7, 1}
c["Le Temple noir"] = {2, 2}
c["Profondeurs de Brassenoire"] = {1, 1}
c["Cavernes de Rochenoire"] = {4, 1}
c["Profondeurs de Rochenoire"] = {1, 1}
c["Fonderie des Rochenoires"] = {6, 2}
c["Descente de l’Aile noire"] = {4, 2}
c["Repaire de l’Aile noire"] = {1, 2}
c["Mine de la Masse-Sanglante"] = {6, 1}
c["Îles Brisées"] = {7, 2}
c["Cour des Étoiles"] = {7, 1}
c["Fourré Sombrecœur"] = {7, 1}
c["Les Mortemines"] = {1, 1}
c["Hache-Tripes"] = {1, 1}
c["Draenor"] = {6, 2}
c["L’Âme des dragons"] = {4, 2}
c["Donjon de Drak’Tharon"] = {3, 1}
c["La Fin des temps"] = {4, 1}
c["L’Œil d’Azshara"] = {7, 1}
c["Terres de Feu"] = {4, 2}
c["Porte du Soleil couchant"] = {5, 1}
c["Gnomeregan"] = {1, 1}
c["Grim Batol"] = {4, 1}
c["Dépôt de Tristerail"] = {6, 1}
c["Repaire de Gruul"] = {2, 2}
c["Gundrak"] = {3, 1}
c["Les salles de Foudre"] = {3, 1}
c["Salles de l’Origine"] = {4, 1}
c["Salles des Reflets"] = {3, 1}
c["Les salles de Pierre"] = {3, 1}
c["Salles des Valeureux"] = {7, 1}
c["Cœur de la peur"] = {5, 2}
c["Citadelle des Flammes infernales"] = {6, 2}
c["Remparts des Flammes infernales"] = {2, 1}
c["Cognefort"] = {6, 2}
c["L’Heure du Crépuscule"] = {4, 1}
c["Citadelle de la Couronne de glace"] = {3, 2}
c["Quais de Fer"] = {6, 1}
c["Karazhan"] = {2, 2}
c["Cité perdue des Tol’vir"] = {4, 1}
c["Bas du pic Rochenoire"] = {1, 1}
c["Terrasse des Magistères"] = {2, 1}
c["Le repaire de Magtheridon"] = {2, 2}
c["Tombes-mana"] = {2, 1}
c["Maraudon"] = {1, 1}
c["La Gueule des âmes"] = {7, 1}
c["Palais Mogu’shan"] = {5, 1}
c["Caveaux Mogu’shan"] = {5, 2}
c["Cœur du Magma"] = {1, 2}
c["Naxxramas"] = {3, 2}
c["Repaire de Neltharion"] = {7, 1}
c["Contreforts de Hautebrande d’antan"] = {2, 1}
c["Repaire d’Onyxia"] = {3, 2}
c["Pandarie"] = {5, 2}
c["Fosse de Saron"] = {3, 1}
c["Gouffre de Ragefeu"] = {1, 1}
c["Souilles de Tranchebauge"] = {1, 1}
c["Kraal de Tranchebauge"] = {1, 1}
c["Ruines d’Ahn’Qiraj"] = {1, 2}
c["Salles Écarlates"] = {1, 1}
c["Monastère Écarlate"] = {1, 1}
c["Scholomance"] = {1, 1}
c["Caverne du sanctuaire du Serpent"] = {2, 2}
c["Les salles des Sethekk"] = {2, 1}
c["Monastère des Pandashan"] = {5, 1}
c["Labyrinthe des Ombres"] = {2, 1}
c["Donjon d’Ombrecroc"] = {1, 1}
c["Terres sacrées d’Ombrelune"] = {6, 1}
c["Siège du temple de Niuzao"] = {5, 1}
c["Siège d’Orgrimmar"] = {5, 2}
c["Orée-du-Ciel"] = {6, 1}
c["Brasserie Brune d’Orage"] = {5, 1}
c["Stratholme"] = {1, 1}
c["Plateau du Puits de soleil"] = {2, 2}
c["Temple d’Ahn’Qiraj"] = {1, 2}
c["Temple du Serpent de jade"] = {5, 1}
c["Terrasse Printanière"] = {5, 2}
c["L’Arcatraz"] = {2, 1}
c["L’Arcavia"] = {7, 1}
c["Le bastion du Crépuscule"] = {4, 2}
c["La bataille du mont Hyjal"] = {2, 2}
c["Le Noir marécage"] = {2, 1}
c["La Fournaise du sang"] = {2, 1}
c["La Botanica"] = {2, 1}
c["L’Épuration de Stratholme"] = {3, 1}
c["Le Cauchemar d’émeraude"] = {7, 2}
c["La Flore éternelle"] = {6, 1}
c["L’Œil"] = {2, 2}
c["L’Œil de l’éternité"] = {3, 2}
c["La Forge des Âmes"] = {3, 1}
c["Le Méchanar"] = {2, 1}
c["Le Nexus"] = {3, 1}
c["Palais Sacrenuit"] = {7, 2}
c["Le sanctum Obsidien"] = {3, 2}
c["L’Oculus"] = {3, 1}
c["Le sanctum Rubis"] = {3, 2}
c["Les salles Brisées"] = {2, 1}
c["Les enclos aux esclaves"] = {2, 1}
c["Le caveau de la Vapeur"] = {2, 1}
c["La Prison"] = {1, 1}
c["Le Cœur-de-Pierre"] = {4, 1}
c["Le temple d’Atal’Hakkar"] = {1, 1}
c["La Basse-tourbière"] = {2, 1}
c["Le fort Pourpre"] = {3, 1}
c["La cime du Vortex"] = {4, 1}
c["Trône du tonnerre"] = {5, 2}
c["Trône des quatre vents"] = {4, 2}
c["Trône des marées"] = {4, 1}
c["L’épreuve du champion"] = {3, 1}
c["L’épreuve du croisé"] = {3, 2}
c["Uldaman"] = {1, 1}
c["Ulduar"] = {3, 2}
c["Sommet du pic Rochenoire"] = {6, 1}
c["Cime d’Utgarde"] = {3, 1}
c["Donjon d’Utgarde"] = {3, 1}
c["Caveau d’Archavon"] = {3, 2}
c["Caveau des Gardiennes"] = {7, 1}
c["Cavernes des Lamentations"] = {1, 1}
c["Puits d’éternité"] = {4, 1}
c["Zul’Aman"] = {4, 1}
c["Zul’Farrak"] = {1, 1}
c["Zul’Gurub"] = {4, 1}
